ToDoTasks/ToDoTask/Controllers/ToDoTasksController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Service.Interfaces;
using ToDoTask.Models.TaskViewModels;

namespace ToDoTask.Controllers
{
    public class ToDoTasksController : Controller
    {
        private readonly IToDoTaskService _service;

        public ToDoTasksController(IToDoTaskService service)
        {
            _service = service;
        }

        // GET: Tasks
        public IActionResult Index()
        {
            return View(_service.GetAllTasks());
        }

        // GET: Tasks/Details
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDoTask = _service.GetTaskById(id.Value);

            if (toDoTask == null)
            {
                return NotFound();
            }

            return View(toDoTask);
        }

        // GET: Tasks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tasks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("UserId, Title, Description, StartDate, EndDate")] TaskCreateModel taskCreateModel)
        {
            if (!ModelState.IsValid)
            {
                return View(taskCreateModel);
            }

            _service.CreateTask(taskCreateModel.UserId, taskCreateModel.Title, taskCreateModel.Description, taskCreateModel.StartDate, taskCreateModel.EndDate);

            return RedirectToAction(nameof(Index));
        }

        // GET: Tasks/Edit
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskToDo = _service.GetTaskById(id.Value);

            if (taskToDo == null)
            {
                return NotFound();
            }

            var taskEditModel = new TaskEditModel(
                taskToDo.Title,
                taskToDo.Description,
                taskToDo.StartDate,
                taskToDo.EndDate
            );

            return View(taskEditModel);
        }

        // POST: Tasks/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("Title, Description, StartDate, EndDate")] TaskEditModel taskEditModel)
        {
            if (!ModelState.IsValid)
            {
                return View(taskEditModel);
            }

            _service.EditTask(id, taskEditModel.Title, taskEditModel.Description, taskEditModel.StartDate, taskEditModel.EndDate);

            return RedirectToAction(nameof(Index));
        }

        // GET: Tasks/Delete
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskToDo = _service.GetTaskById(id.Value);

            if (taskToDo == null)
            {
                return NotFound();
            }

            return View(taskToDo);
        }

        // POST: Tasks/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _service.DeleteTask(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

ToDoTasks/ToDoTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoTasks</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-primary navbar-dark fixed-top justify-content-between">
        <div class="container">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ToDo Tasks</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Explore</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-area="" asp-controller="ToDoTasks" asp-action="Index">Tasks</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle disabled" data-toggle="dropdown" href="#">Community</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Friend's tasks</a>
                        <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">People</a>
                    </div>
                </li>
            </ul>
            
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>